spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interview_managerment
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Nhuan1965@

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 8bb3e3068eaa2d
    password: bf45746d133129
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl: yes
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:db/data.sql

